server:
  port: 4004

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
            allowCredentials: true
      server:
        webflux:
          routes:
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

# in the below filter JwtValidation is a custom filter defined in gateway application
# So, the SB gateway will immediately call the class = custom_filter_name(JwtValidation)+GatewayFilterFactory
# i.e for current patient-service it calls JwtValidationGatewayFilterFactory
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients,/api/patients/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs

            - id: api-docs-auth-route
              uri: http://auth-service:4005
              predicates:
                - Path=/api-docs/auth
              filters:
                - RewritePath=/api-docs/auth,/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      access: read_only