spring.application.name=patient-service

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:patientdb;
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=test
spring.datasource.password=test

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
# optional: explicitly set the Hibernate dialect for H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
# always check entity classes against database tables
spring.sql.init.mode=always

server.port=4000
